version: "2"

services:
  web:
    build: .
    depends_on:
    - mongo
    environment:
      - AUTO_LOGIN=
      - CALENDAR_ID=
      - TIME_ZONE=
      - IMPORTANT_EVENT_COLOR_ID=
      - TOKEN_ID=
    restart: always

  mongo:
    image: mongo
    restart: always